<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="2.414" timestamp="2025-06-25T22:54:14.712688-03:00" hostname="DESKTOP-QHMPTGO"><testcase classname="" name="archivos_eliminados_20250625_224359.test_results.test_terminal_output.txt" time="0.000"><error message="collection failure">..\..\..\AppData\Local\Programs\Python\Python313\Lib\pathlib\_local.py:546: in read_text
    return PathBase.read_text(self, encoding, errors, newline)
..\..\..\AppData\Local\Programs\Python\Python313\Lib\pathlib\_abc.py:633: in read_text
    return f.read()
&lt;frozen codecs&gt;:325: in decode
    ???
E   UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte</error></testcase></testsuite></testsuites>
